In [229]:
import numpy as np
import math  as mth

In [230]:
#array of inputs and outputs 
#used in training and prediction 
inputs = [[1,1], 
          [1,0], 
          [0,1], 
          [0,0]]

outputs = [1,
           0,
           0,
           0]
print(inputs)
print(outputs)

[[1, 1], [1, 0], [0, 1], [0, 0]]
[1, 0, 0, 0]


In [231]:
class SGD_Perceptron :
    # initializing the perceptron 
    def __init__(self,num_features,iterations=500,learning_rate=0.01):
        self.iterations = iterations 
        self.learning_rate = learning_rate
        # np.zeros to initialize with zeros
        # +1 because threshold will be considered as an input with weights 
        self.weights = np.zeros(num_features + 1)
        
    # prediction function
    def predict(self, inputs):
        # np.dot to times each input with corresponding weight 
        # threshold in weight[0] (first place of array)
        s_dash = np.dot(inputs, self.weights[1:]) + self.weights[0]
        
        # sigmoid function 
        exponent = s_dash*(-1)
        # exp is e^exponent
        y = 1 / (1 + mth.exp(exponent))
        return y
        
    # training function    
    def train(self, training_inputs, labels):
        for _ in range(self.iterations):
            for inputs, desired in zip(training_inputs, labels): # zip combine values that correspond in 2 arrays 
                prediction = self.predict(inputs)
                # updating weights with maximum cross entropy 
                self.weights[1:] += self.learning_rate * (desired - prediction) * inputs
                # updating threshold 
                self.weights[0] += self.learning_rate * (desired - prediction) 
        
        print(self.weights)
        
    

In [232]:
training_inputs = np.array([[1,1],[1,0],[0,1],[0,0]]) #no builtin array therefore must use np.array()
print (training_inputs)

[[1 1]
 [1 0]
 [0 1]
 [0 0]]


In [233]:
labels = np.array([1, 0, 0, 0])
print (labels)

[1 0 0 0]


In [234]:
P = SGD_Perceptron(2)
P.train(training_inputs,labels)

[-1.92267183  1.01988884  1.02210566]


In [238]:
inputs = np.array([1, 0])

print("Input sample is: ", inputs)

print("Perceptron prediction is (before logical represenation): ", P.predict(inputs)) 

#with increased iterations we get closer to 1 or 0 with 10k iterations the predict value (y) was 0.92 for logic 1
#and 0.04 for logic 0
if (P.predict(inputs)>0.5):
    out=1 #to represent the o/p logically sigmoid will never reach perfect 1 or 0 must increase iterations drastically       #
else:
    out=0

print("Perceptron prediction is: ", out )

Input sample is:  [1 0]
Perceptron prediction is (before logical represenation):  0.28847892956077525
Perceptron prediction is:  0
